#!/bin/bash

CMAKE_DIR=`pwd`
BUILD_DIR="${B_HOME}/_build"
INSTALL_DIR="${B_HOME}/_install/"
PROJECT=$0

function build() {
 rm -rf $BUILD_DIR
 rm -rf $INSTALL_DIR
 mkdir $BUILD_DIR
 mkdir $INSTALL_DIR
 cd $BUILD_DIR
 cmake $CMAKE_DIR
}

if [[ ! -d "$B_HOME" ]]; then
  "No B_HOME dir found at ${B_HOME}, creating..."
  mkdir $B_HOME
fi

if [[ -d "$INSTALL_DIR" ]]; then
  build
else
  echo "No install dir found at ${INSTALL_DIR}, creating..."
  mkdir $INSTALL_DIR
  build
fi
